### PR TITLE
Merge hunspell

### PR DESCRIPTION
**Pull request by nathanjsweet**
Don't merge yet. Let's wait to see if the hunspell project merges my PR.

### CODE REVIEW

**Comment by nathanjsweet** [comment]
Looks like they don't want to merge my hunspell changes as they are freezing hunspell and starting new work on hunspell2. Looks like some RedHat folks behind it, so we should keep a sharp eye as I bet there are some fun developments.

We'll just use my fork for now, once I get these integration failures figured out. @Wulf  any insight into these failures?

**Comment by trofim24** [comment]
Clear. We then remain on our fork.
Why? Because 'hunspell-distributed' falls on windows x64 with 30 dictionaries.

**Comment by Wulf** [comment]
Hunspell2, wowow.

@nathanjsweet Your changes are fine, we can merge this in. 

The failure is happening because the OS X builds on travis can't compile the native code because it apparently doesn't exist.

```
CXX(target) Release/obj.target/hunspell/src/hunspell/src/hunspell/affentry.o
make: g++-4.8: No such file or directory
```

This problem isn't specific to this PR, it's something to do with the [.travis.yml](https://github.com/Wulf/nodehun/blob/master/.travis.yml) file.

**Comment by nathanjsweet** [comment]
@trofim24 no, we updated to latest in hunspell, and I added the new interface work. Because it's a straight fork in git it will be much, much easier to keep up to date with the original repo when there are changes.

**Pull request merged**
